#!/bin/bash

RCM_EXTENSION_VERSION=0.2.0-alpha.2

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm-certbot-obtain [options]

Options:
   --domain=[DOMAIN]...
        Set the domain.
   --authenticator-plugin=PLUGIN
        Select how to authenticate domain.
        Values available from command: rcm(plugin list certbot/authenticator).
   --certificate-name=[NAME]
        Use the existing certificate name that issued by Let's encrypt or set a
        new name of certificate that to be obtained.
        Prepopulate value from variable CERTIFICATE_NAME.
        Left blank will use auto set by certbot, usually the FQDN (with an integer suffix in case of conflict).
   --email=[EMAIL]
        Email contact of certbot account.

Additional Options:
   rcm(-p plugin prompt certbot/authenticator [--authenticator-plugin] init)
   rcm(-p plugin prompt certbot/authenticator [--authenticator-plugin] is-domain-exists)
   rcm(-p plugin prompt certbot/authenticator [--authenticator-plugin] append-arguments)

Global Options.
   --version
        Print version of this script.
   --help
        Show this help.

RCM Config:
   --no-timer
   --no-confirmation
EOF
}

# Prevent scripts from being executed directly.
[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --authenticator-plugin=*) authenticator_plugin="${1#*=}"; shift ;;
        --authenticator-plugin) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then authenticator_plugin="$2"; shift; fi; shift ;;
        --certificate-name=*) certificate_name="${1#*=}"; shift ;;
        --certificate-name) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then certificate_name="$2"; shift; fi; shift ;;
        --domain=*) domain+=("${1#*=}"); shift ;;
        --domain) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then domain+=("$2"); shift; fi; shift ;;
        --email=*) email="${1#*=}"; shift ;;
        --email) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then email="$2"; shift; fi; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

require vendor/ijortengab/rcm/functions/base/array.sh
require vendor/ijortengab/rcm/functions/classes/rcm-yaml.sh

# ------------------------------------------------------------------------------

# Title.
title rcm certbot obtain
____

# Dependency.
require command certbot

# Require, validate, and populate value.
chapter Variable dump.
is_domain_array=()
e; magenta 'domain=('
first=1
for each in "${domain[@]}";do
    if [ -n "$first" ];then
        magenta "'""$each""'"; first=
    else
        magenta " '""$each""'";
    fi
    is_domain_array+=("--domain=${each}")
done
magenta ')'; _.
code 'certificate_name="'$certificate_name'"'
[ -n "$certificate_name" ] && is_certificate_name=" --cert-name=${certificate_name}" || is_certificate_name=
[ -n "$email" ] && is_email=" --email=${email}" || is_email=
code 'email="'$email'"'
code 'authenticator_plugin="'$authenticator_plugin'"'
if [[ "${#domain[@]}" -eq 0 ]];then
    error Argument --domain is required.; x
fi
if [ -z "$authenticator_plugin" ];then
    error Argument --authenticator-plugin is required.; x
fi
tempfile=
____

include `rcm plugin run-method certbot/authenticator $authenticator_plugin init`

RCM_FQDN="$domain"
include `rcm plugin run-method certbot/authenticator $authenticator_plugin is-domain-exists`

RCM_CERTBOT_ARGUMENTS=()
include `rcm plugin run-method certbot/authenticator $authenticator_plugin append-arguments`

chapter Obtain Certificate.
if [ -z "$tempfile" ];then
    tempfile=$(mktemp -p /dev/shm -t rcm-certbot-obtain.XXXXXX)
fi
# https://eff-certbot.readthedocs.io/en/latest/using.html#combination
msg='Another instance of Certbot is already running.'
if [ "${#RCM_CERTBOT_ARGUMENTS[@]}" -gt 0 ];then
    set -- "${RCM_CERTBOT_ARGUMENTS[@]}"
fi
unset append_arguments
while true; do
    code certbot -v certonly"$is_certificate_name""$is_email" --non-interactive --agree-tos \
        "${is_domain_array[@]}" \
        "$@"
    certbot -v certonly $is_certificate_name $is_email --non-interactive --agree-tos \
        "${is_domain_array[@]}" \
        "$@" &> "$tempfile"
    if [[ $(head -1 "$tempfile") == "$msg" ]];then
        e Retrying...; _.
        code sleep 3
        sleep 3
    else
        break
    fi
done

if [ -s "$tempfile" ];then
    while IFS= read -r line; do
        e "$line"; _.
    done < "$tempfile"
fi
____

[ -n "$tempfile" ] && rm "$tempfile"
____

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# --certificate-name
# --email
# --authenticator-plugin
# )
# MULTIVALUE=(
# --domain
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# EOF
# clear
