#!/bin/bash

RCM_EXTENSION_VERSION=0.1.3-alpha.6

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm-nginx-certbot-authenticator-plugin [options]

Global Options.
   --version
        Print version of this script.
   --help
        Show this help.

EOF
}

# Prevent scripts from being executed directly.
[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --) shift
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        --[^-]*) shift ;;
        plugin)
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Command.
if [ -n "$1" ];then
    command=
    case "$1" in
        plugin) command="$1"; shift ;;
    esac
    if [ -z "$command" ];then
        error Command unknown: '`'"$1"'`'.; x
    fi
fi

# Define variables and constants.
if [ -n "$RCM_VERBOSE" ];then
    verbose="$RCM_VERBOSE"
fi
[[ -z "$verbose" || "$verbose" -lt 1 ]] && quiet=1 || quiet=
[[ "$verbose" -gt 0 ]] && loud=1
[[ "$verbose" -gt 1 ]] && loud=1 && louder=1
[[ "$verbose" -gt 2 ]] && loud=1 && louder=1 && debug=1

# Help and Version.
[ -n "$help" ] && { usage; exit 1; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

command-plugin() {
    local interface=$1 name=$2 method=$3
    local function="plugin-${interface}-${name}-$method"
    if [[ $(type -t "${function}") == function ]];then
        title "rcm-nginx-certbot-authenticator-plugin::plugin-${interface}-${name}-${method}()"
        ____

        ${function}
        exit 0
    else
        error The function of method '`'"$function"'`' has not yet defined.; x
    fi
}
plugin-certbot_authenticator-nginx-prompt() {
    return 0
}
plugin-certbot_authenticator-nginx-install() {
    return 0
}
plugin-certbot_authenticator-nginx-append_arguments() {
    echo '--nginx'
}

# Execute command.
if [ -n "$command" ];then
    if [[ $(type -t "command-${command}") == function ]];then
        command-${command} "$@"
        exit 0
    else
        error The function of command '`'"$command"'`' has not yet defined.; x
    fi
fi

usage >/dev/null | head -3
_ Try; blue ' 'rcm-nginx-certbot-authenticator-plugin; magenta ' '--help; _, ' 'for more information.; _.

exit 0

# parse-options.sh \
# --with-end-options-specific-operand \
# --with-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# INCREMENT=(
# )
# FLAG=(
# --version
# --help
# )
# VALUE=(
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# OPERAND=(
# plugin
# )
# EOF
# clear
