#!/bin/bash

RCM_EXTENSION_VERSION=0.1.3-alpha.6

# Common Functions.
red() { echo -ne "\e[91m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
green() { echo -ne "\e[92m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
yellow() { echo -ne "\e[93m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
blue() { echo -ne "\e[94m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
magenta() { echo -ne "\e[95m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
error() { echo -n "$INDENT" >&2; red '#' "$@" >&2; echo >&2; }
success() { echo -n "$INDENT" >&2; green '#' "$@" >&2; echo >&2; }
chapter() { echo -n "$INDENT" >&2; yellow '#' "$@" >&2; echo >&2; }
title() { echo -n "$INDENT" >&2; blue '#' "$@" >&2; echo >&2; }
code() { echo -n "$INDENT" >&2; magenta "$@" >&2; echo >&2; }
x() { echo >&2; exit 1; }
e() { echo -n "$INDENT" >&2; echo -n "$@" >&2; }
_() { echo -n "$INDENT" >&2; echo -n "#"' ' >&2; [ -n "$1" ] && echo -n "$@" >&2; }
_,() { echo -n "$@" >&2; }
_.() { echo >&2; }
__() { echo -n "$INDENT" >&2; echo -n "# ${RCM_INDENT}" >&2; [ -n "$1" ] && echo "$@" >&2; }
____() { echo >&2; [ -n "$RCM_DELAY" ] && sleep "$RCM_DELAY"; }

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --fast) fast=1; shift ;;
        --) shift
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        --[^-]*) shift ;;
        plugin|prompt)
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Command.
if [ -n "$1" ];then
    command=
    case "$1" in
        plugin) command="$1"; shift ;;
        prompt) command="$1"; shift ;;
    esac
    if [ -z "$command" ];then
        error Command unknown: '`'"$1"'`'.; x
    fi
fi

# Parse arguments per command. Generated by parse-options.sh
case "$command" in
    prompt)
        _new_arguments=()
        while [[ $# -gt 0 ]]; do
            case "$1" in
                --help) help=1; shift ;;
                --version) version=1; shift ;;
                --certbot-certificate-name=*) certbot_certificate_name="${1#*=}"; shift ;;
                --certbot-certificate-name) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then certbot_certificate_name="$2"; shift; fi; shift ;;
                --certbot-authenticator-plugin=*) certbot_authenticator_plugin="${1#*=}"; shift ;;
                --certbot-authenticator-plugin) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then certbot_authenticator_plugin="$2"; shift; fi; shift ;;
                --fast) fast=1; shift ;;
                --[^-]*) shift ;;
                *) _new_arguments+=("$1"); shift ;;
            esac
        done
        set -- "${_new_arguments[@]}"
        unset _new_arguments
esac

# Define variables and constants.
[ -z "$fast" ] && fast="$RCM_FAST"; [ "$fast" == 0 ] && fast=
RCM_DELAY=${RCM_DELAY:=.5}; [ -n "$fast" ] && unset RCM_DELAY
RCM_INDENT='    '; [ "$(tput cols)" -le 80 ] && RCM_INDENT='  '
[ -z "$fast" ] && isfast='' || isfast=' --fast'
if [ -n "$RCM_VERBOSE" ];then
    verbose="$RCM_VERBOSE"
fi
[[ -z "$verbose" || "$verbose" -lt 1 ]] && quiet=1 || quiet=
[[ "$verbose" -gt 0 ]] && loud=1
[[ "$verbose" -gt 1 ]] && loud=1 && louder=1
[[ "$verbose" -gt 2 ]] && loud=1 && louder=1 && debug=1

# Functions. Help and Version.
usage() {
    title RCM TLS Plugin
    _ 'Variation '; yellow Certbot; _.
    _.
    cat << EOF
Usage: rcm-certbot-tls-plugin [options]

Options for command prompt:
   --certbot-certificate-name
        Use the existing certificate name that issued by Let's encrypt or set a
        new name of certificate that to be obtained.
        Prepopulate value from variable CERTBOT_CERTIFICATE_NAME.
        Left blank will use auto set by certbot, usually the FQDN (with an integer suffix in case of conflict).
   --certbot-authenticator-plugin *
        Select how to authenticate domain.
        Values available from command: rcm-plugin(list --interface=certbot_authenticator).
        Prepopulate value from variable CERTBOT_AUTHENTICATOR_PLUGIN.

Global Options.
   --fast
        No delay every subtask.
   --version
        Print version of this script.
   --help
        Show this help.

Download:
   [rcm-certbot-tls-plugin](https://github.com/ijortengab/rcm-certbot/raw/master/rcm/certbot/rcm-certbot-tls-plugin.sh)
   [rcm-certbot-apt](https://github.com/ijortengab/rcm-certbot/raw/master/rcm/certbot/rcm-certbot-apt.sh)
   [rcm-certbot-obtain](https://github.com/ijortengab/rcm-certbot/raw/master/rcm/certbot/rcm-certbot-obtain.sh)
   [rcm-nginx-certbot-authenticator-plugin](https://github.com/ijortengab/rcm-certbot/raw/master/rcm/nginx/rcm-nginx-certbot-authenticator-plugin.sh)

Dependency:
   rcm-certbot-apt:`printVersion`
   rcm-certbot-obtain:`printVersion`

Pre Prompt:
   rcm-plugin(init --interface=certbot_authenticator)

Post Install:
   rcm-plugin(add --interface=certbot_authenticator --name=nginx --command=rcm-nginx-certbot-authenticator-plugin --version=`printVersion`)
   rcm-install(nginx-certbot-authenticator-plugin `printVersion` --source=certbot-tls-plugin)

Post Update:
   rcm-plugin(add --interface=certbot_authenticator --name=nginx --command=rcm-nginx-certbot-authenticator-plugin --version=`printVersion`)
   rcm-update(nginx-certbot-authenticator-plugin `printVersion` --source=certbot-tls-plugin)

RCM Config:
   --no-timer
   --no-confirmation
EOF
}

# Help and Version.
[ -n "$help" ] && { usage; exit 1; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

isFileExists() {
    # global used:
    # global modified: found, notfound
    # function used: __
    found=
    notfound=
    if [ -f "$1" ];then
        __ File '`'$(basename "$1")'`' ditemukan.
        found=1
    else
        __ File '`'$(basename "$1")'`' tidak ditemukan.
        notfound=1
    fi
}
ArraySearch() {
    local index match="$1"
    local source=("${!2}")
    for index in "${!source[@]}"; do
       if [[ "${source[$index]}" == "${match}" ]]; then
           _return=$index; return 0
       fi
    done
    return 1
}
Rcm_certbot() {
    # Global, untuk debug.
    local certbot_request line cache_file_basename
    local start end runtime line_number
    local expired="$1"
    local url="$2"
    local table=$HOME/.cache/rcm/rcm.table.cache
    local table_lock=$HOME/.cache/rcm/rcm.table.cache.lock
    local cache_file=
    local do_delete_record_cache_file=
    chapter Certbot certificates information
    _Rcm_certbot() {
        if [ -f "$table" ];then
            # todo, cek jika multiline.
            line=$(grep -n -F "$url"' ' "$table")
            if [ -z "$line" ];then
                certbot_request=1
            else
                cache_file_basename=$(cut -d' ' -f2 <<< "$line")
                cache_file=$HOME/.cache/rcm/"$cache_file_basename"
            fi
        else
            certbot_request=1
        fi
        if [ -n "$cache_file" ];then
            if [ -f "$cache_file" ];then
                if [ -s "$cache_file" ];then
                    start=`date -r "$cache_file" +'%s'`
                    end=`date +%s`
                    runtime=$((end-start))
                    if [ $runtime -gt $expired ];then
                        do_delete_record_cache_file=1
                    fi
                else
                    do_delete_record_cache_file=1
                fi
            else
                do_delete_record_cache_file=1
            fi
        fi
        if [ -n "$do_delete_record_cache_file" ];then
            line_number=$(cut -d':' -f1 <<< "$line")
            sed -i $line_number'd' "$table"
            certbot_request=1
            if [ -f "$cache_file" ];then
                rm "$cache_file"
            fi
            cache_file=
        fi
        exit_code=0
        if [ -n "$certbot_request" ];then
            mkdir -p $HOME/.cache/rcm
            cache_file=$(mktemp --tmpdir=$HOME/.cache/rcm rcm.certbot.XXXXXXXXXXXX.cache)
            cache_file_basename=$(basename "$cache_file")
            certificate_name=$(sed 's|certbot://||' <<< "$url")
            msg='Another instance of Certbot is already running.'
            while true; do
                code certbot certificates --cert-name="$certificate_name"
                certbot certificates --cert-name="$certificate_name" 2>/dev/null > "$cache_file"
                exit_code=$?
                if [[ $(head -1 "$cache_file") == "$msg" ]];then
                    e Retrying...; _.
                    code sleep 3
                    sleep 3
                else
                    break
                fi
            done
            mkdir -p $(dirname "$table")
            echo "$url" "$cache_file_basename" >> "$table"
        fi
    }
    until [[ ! -e "$table_lock" ]];do
        sleep .1
        # Jika lebih dari 1 menit, maka hapus saja.
        start=`date -r "$table_lock" +'%s'`
        end=`date +%s`
        runtime=$((end-start))
        if [ $runtime -gt 60 ];then
            rm "$table_lock"
        fi
    done
    touch "$table_lock"
    _Rcm_certbot
    rm "$table_lock"
    ____

    if [ ! -f "$cache_file" ];then
        exit $exit_code
    fi
    if [ ! $exit_code -eq 0 ];then
        exit $exit_code
    fi
    cat "$cache_file"
}
command-prompt() {
    # If not set in argument, try load from environment.
    [ -z "$certbot_certificate_name" ] && certbot_certificate_name="$CERTBOT_CERTIFICATE_NAME"
    # Export.
    echo 'CERTBOT_CERTIFICATE_NAME='"$certbot_certificate_name"
    # Plugin certbot_authenticator juga perlu di cetak, termasuk init nya, dan prompt nya.
    # It must set in argument, because of required.
    # todo error.
    echo 'CERTBOT_AUTHENTICATOR_PLUGIN='"$certbot_authenticator_plugin"
    INDENT+='    '
    rcm-plugin $isfast execute --interface=certbot_authenticator --name="$certbot_authenticator_plugin" \
        --method='prompt' \
        ; [ ! $? -eq 0 ] && x
    read -ra array -d '' <<< "$RCM_ENVIRONMENT_VARIABLES"
    for each in "${array[@]}"; do
        echo "$each"
    done
}
command-plugin() {
    local interface=$1 name=$2 method=$3
    local function="plugin-${interface}-${name}-$method"
    if [[ $(type -t "${function}") == function ]];then
        title "rcm-certbot-tls-plugin::plugin-${interface}-${name}-${method}()"
        ____

        ${function}
        exit 0
    else
        error The function of method '`'"$function"'`' has not yet defined.; x
    fi
}
plugin-tls-certbot-prompt() {
    INDENT+='    ' \
    rcm certbot-tls-plugin prompt
}
plugin-tls-certbot-server_setup_post() {
    INDENT+='    ' \
    rcm-certbot-apt $isfast \
    ; [ ! $? -eq 0 ] && x

    # If not set in argument, try load from environment.
    [ -z "$certbot_authenticator_plugin" ] && certbot_authenticator_plugin="$CERTBOT_AUTHENTICATOR_PLUGIN"

    # Cleaning environment variable from rcm.
    INDENT+='    ' \
    rcm-plugin $isfast execute --interface=certbot_authenticator --name="$certbot_authenticator_plugin" --method='install' --ignore-fail-on-empty-name \
    ; [ ! $? -eq 0 ] && x
}
plugin-tls-certbot-obtain_certificate() {
    [[ $(type -t ArraySearch) == function ]] || { error Function ArraySearch not found.; x; }
    [[ $(type -t Rcm_certbot) == function ]] || { error Function Rcm_certbot not found.; x; }
    [[ $(type -t isFileExists) == function ]] || { error Function isFileExists not found.; x; }
    # Load from environment.
    [ -n "$RCM_FQDN" ] || { error Environment Variable RCM_FQDN required; x; }
    local fqdn="$RCM_FQDN"
    local certificate_name="$CERTBOT_CERTIFICATE_NAME"
    local authenticator_plugin="$CERTBOT_AUTHENTICATOR_PLUGIN"

    # Cleaning environment variable from rcm.
    [ "$certificate_name" == - ] && certificate_name=

    chapter Variable dump.
    code 'fqdn="'$fqdn'"'
    code 'certificate_name="'$certificate_name'"'
    [ -z "$certificate_name" ] && certificate_name="$fqdn"
    code 'certificate_name="'$certificate_name'"'
    ____

    chapter Mengecek '$PATH'.
    code PATH="$PATH"
    if grep -q '/snap/bin' <<< "$PATH";then
        __ '$PATH' sudah lengkap.
    else
        __ '$PATH' belum lengkap.
        __ Memperbaiki '$PATH'
        PATH=/snap/bin:$PATH
        if grep -q '/snap/bin' <<< "$PATH";then
            __; green '$PATH' sudah lengkap.; _.
            __; magenta PATH="$PATH"; _.
        else
            __; red '$PATH' belum lengkap.; x
        fi
    fi
    ____

    [ -z "$tempfile" ] && tempfile=$(mktemp -p /dev/shm -t rcm-certbot-tls-plugin.XXXXXX)
    Rcm_certbot 600 "certbot://${certificate_name}" > "$tempfile"

    chapter Mengecek certificate '`'$certificate_name'`'.
    certificate_path=$(cat "$tempfile" | grep -i -E 'Certificate Path:\s+' | sed -E 's/Certificate Path:\s+(.*)/\1/' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
    private_key_path=$(cat "$tempfile" | grep -i -E 'Private Key Path:\s+' | sed -E 's/Private Key Path:\s+(.*)/\1/' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
    code 'certificate_path="'$certificate_path'"'
    code 'private_key_path="'$private_key_path'"'
    binary=
    notfound=1

    [ -n "$certificate_path" ] && isFileExists "$certificate_path"
    [ -n "$notfound" ] && binary+=0
    notfound=1
    [ -n "$private_key_path" ] && isFileExists "$private_key_path"
    [ -n "$notfound" ] && binary+=0
    ____

    if [[ "$binary" =~ 0 ]];then
        INDENT+='    ' \
        rcm-certbot-obtain $isfast \
            --certificate-name="$certificate_name" \
            --domain="$fqdn" \
            --authenticator-plugin="$authenticator_plugin" \
            ; [ ! $? -eq 0 ] && x

        # Reload and flush the cache.
        Rcm_certbot 0 "certbot://${certificate_name}" > "$tempfile"
        certificate_path=$(cat "$tempfile" | grep -i -E 'Certificate Path:\s+' | sed -E 's/Certificate Path:\s+(.*)/\1/' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        private_key_path=$(cat "$tempfile" | grep -i -E 'Private Key Path:\s+' | sed -E 's/Private Key Path:\s+(.*)/\1/' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
    fi

    # Certificate ditemukan, maka berikutnya kita perlu verifikasi lagi.
    chapter Verifikasi Domain
    _list_domain=$(cat "$tempfile" | grep -i -E 'Domains:\s+' | sed -E 's/Domains:(.*)/\1/')
    # Jika variable $_list_domain terdapat karakter wildcard, maka:
    # list_domain=($_list_domain)
    read -ra list_domain -d '' <<< "$_list_domain"
    # Dump array dengan single quote.
    e; magenta 'list_domain=('
    first=1
    for each in "${list_domain[@]}";do
        if [ -n "$first" ];then
            magenta "'""$each""'"; first=
        else
            magenta " '""$each""'";
        fi
    done
    magenta ')'; _.
    __ Mengecek domain '`'"$fqdn"'`'
    found=
    if ArraySearch "$fqdn" list_domain[@];then
        found=1
        __ Domain ditemukan.
    else
        __ Domain tidak ditemukan.
    fi
    if [ -z "$found" ];then
        __ Mengecek versi wildcard dari domain '`'"$fqdn"'`'
        IFS='.' read -ra array <<< "$fqdn"
        if [ "${#array[@]}" -gt 2 ];then
            domain_wildcard=
            first=1
            for each in "${array[@]}"; do
                if [ -n "$first" ];then
                    domain_wildcard='*'
                    first=
                else
                    domain_wildcard+=".${each}"
                fi
            done
            code 'domain_wildcard="'$domain_wildcard'"'
            if ArraySearch "$domain_wildcard" list_domain[@];then
                found=1
                __ Wildcard domain ditemukan.
            else
                __ Wildcard domain tidak ditemukan.
            fi

        else
            __ Domain bukan merupakan subdomain.
        fi
    fi

    if [ -z "$found" ];then
        e; red Coming Soon; _.
        # pake function aja
        return
    fi

    __ Domain terdaftar pada certificate.
    ____

    echo 'TLS_CERTIFICATE='"$certificate_path"
    echo 'TLS_CERTIFICATE_KEY='"$private_key_path"
}

# Execute command.
if [ -n "$command" ];then
    if [[ $(type -t "command-${command}") == function ]];then
        command-${command} "$@"
        exit 0
    else
        error The function of command '`'"$command"'`' has not yet defined.; x
    fi
fi

exit 0

# parse-options.sh \
# --with-end-options-specific-operand \
# --with-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# INCREMENT=(
# )
# FLAG=(
# --fast
# --version
# --help
# )
# VALUE=(
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# OPERAND=(
# plugin
# prompt
# )
# EOF
# clear

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --fast
# --version
# --help
# )
# VALUE=(
# --certbot-certificate-name
# --certbot-authenticator-plugin
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# EOF
# clear
