#!/bin/bash

RCM_EXTENSION_VERSION=0.1.3-alpha.6

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm certbot init

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.
EOF
}

# Prevent scripts from being executed directly.
[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# Require.
require vendor/ijortengab/rcm/functions/utility/apt-install.sh

# ------------------------------------------------------------------------------

# Title.
title rcm certbot init
____

apt-install snapd

command -v "snap" >/dev/null || {
    [ -f /etc/profile.d/apps-bin-path.sh ] && . /etc/profile.d/apps-bin-path.sh
}

chapter Mengecek apakah snap core installed.
notfound=
if grep -q '^core\s' <<< $(snap list core);then
    __ Snap core installed.
else
    __ Snap core not found.
    notfound=1
fi
____

if [ -n "$notfound" ];then
    chapter Menginstall snap core
    code snap install core
    code snap refresh core
    snap install core
    snap refresh core
    if grep -q '^core\s' <<< $(snap list core);then
        __; green Snap core installed.; _.
    else
        __; red Snap core not found.; x
    fi
    ____
fi

chapter Mengecek apakah snap certbot installed.
notfound=
if grep -q '^certbot\s' <<< $(snap list certbot);then
    __ Snap certbot installed.
else
    __ Snap certbot not found.
    notfound=1
fi
____

if [ -n "$notfound" ];then
    chapter Menginstall snap certbot
    code snap install --classic certbot
    snap install --classic certbot
    snap set certbot trust-plugin-with-root=ok
    if grep -q '^certbot\s' <<< $(snap list certbot);then
        __; green Snap certbot installed.; _.
    else
        __; red Snap certbot not found.; x
    fi
    ____
fi

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# EOF
# clear
