#!/bin/bash

RCM_EXTENSION_VERSION=0.1.3-alpha.6

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm-certbot [options]

Global Options.
   --version
        Print version of this script.
   --help
        Show this help.

Dependency:
   rcm:0.18.0-alpha.5

Download:
   [rcm-certbot](https://github.com/ijortengab/rcm-certbot/raw/master/rcm/rcm-certbot.sh)
   [rcm-certbot-tls-plugin](https://github.com/ijortengab/rcm-certbot/raw/master/rcm/certbot/rcm-certbot-tls-plugin.sh)

Post Install:
   rcm-plugin(add --interface=tls --name=certbot --command=rcm-certbot-tls-plugin --version=`printVersion`)
   rcm-install(certbot-tls-plugin `printVersion` --source=certbot)

Post Update:
   rcm-plugin(add --interface=tls --name=certbot --command=rcm-certbot-tls-plugin --version=`printVersion`)
   rcm-update(certbot-tls-plugin `printVersion` --source=certbot)

RCM Config:
   --no-timer
   --no-confirmation
EOF
}

# Prevent scripts from being executed directly.
[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --) shift
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

exit 0

# parse-options.sh \
# --with-end-options-specific-operand \
# --with-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# INCREMENT=(
# )
# FLAG=(
# --version
# --help
# )
# VALUE=(
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# OPERAND=(
# )
# EOF
# clear
